import type { FullCompanyAnalysis } from "../ai/company-schemas";

/**
 * A single, clearly-labeled illustrative demo company — shown when
 * DEMO_MODE=true or no ANTHROPIC_API_KEY is set, exactly like
 * lib/demo-data/*.ts does for the startup side. "Aperture Industrial
 * Robotics" is fictional; it exists only so the UI has something real to
 * render with zero setup. It is never presented as a real filer — every
 * screen that shows it also shows a DEMO DATA badge (see isDemoData).
 */
export const DEMO_COMPANY_ANALYSIS: FullCompanyAnalysis = {
  id: "demo-company-aptr",
  input: { ticker: "DEMO" },
  isDemoData: true,
  createdAt: new Date().toISOString(),
  financials: {
    companyName: "Aperture Industrial Robotics, Inc. (ILLUSTRATIVE DEMO — not a real SEC filer)",
    ticker: "DEMO",
    cik: "0000000000",
    sector: "Industrial Machinery (demo)",
    price: 84.5,
    priceAsOf: "2025-09-15 (demo)",
    priceSource: "DEMO DATA — illustrative, not a real quote",
    marketCap: 21_400_000_000,
    revenueLatest: 3_120_000_000,
    revenueFiscalYear: 2024,
    netIncomeLatest: 412_000_000,
    epsLatest: 1.63,
    metrics: {
      revenue_growth_yoy: { value: 0.19, confidence: "estimate", source: "DEMO DATA", note: "Illustrative only." },
      revenue_cagr_3y: { value: 0.21, confidence: "estimate", source: "DEMO DATA" },
      revenue_cagr_5y: { value: 0.17, confidence: "estimate", source: "DEMO DATA" },
      eps_growth_yoy: { value: 0.24, confidence: "estimate", source: "DEMO DATA" },
      gross_margin: { value: 0.58, confidence: "estimate", source: "DEMO DATA" },
      operating_margin: { value: 0.22, confidence: "estimate", source: "DEMO DATA" },
      net_margin: { value: 0.132, confidence: "estimate", source: "DEMO DATA" },
      free_cash_flow: { value: 540_000_000, confidence: "estimate", source: "DEMO DATA" },
      fcf_margin: { value: 0.173, confidence: "estimate", source: "DEMO DATA" },
      fcf_conversion: { value: 1.31, confidence: "estimate", source: "DEMO DATA" },
      roe: { value: 0.19, confidence: "estimate", source: "DEMO DATA" },
      roic: { value: 0.165, confidence: "estimate", source: "DEMO DATA" },
      net_debt: { value: -380_000_000, confidence: "estimate", source: "DEMO DATA", note: "Negative = net cash position." },
      debt_to_equity: { value: 0.22, confidence: "estimate", source: "DEMO DATA" },
      pe_ratio: { value: 31.8, confidence: "estimate", source: "DEMO DATA" },
      ps_ratio: { value: 6.9, confidence: "estimate", source: "DEMO DATA" },
      pb_ratio: { value: 6.1, confidence: "estimate", source: "DEMO DATA" },
      ev_to_sales: { value: 6.7, confidence: "estimate", source: "DEMO DATA" },
      ev_to_ebitda_approx: { value: 27.4, confidence: "estimate", source: "DEMO DATA" },
      fcf_yield: { value: 0.025, confidence: "estimate", source: "DEMO DATA" },
    },
    revenueHistory: [
      { fiscalYear: 2020, value: 1_540_000_000 },
      { fiscalYear: 2021, value: 1_890_000_000 },
      { fiscalYear: 2022, value: 2_260_000_000 },
      { fiscalYear: 2023, value: 2_620_000_000 },
      { fiscalYear: 2024, value: 3_120_000_000 },
    ],
    netIncomeHistory: [
      { fiscalYear: 2020, value: 118_000_000 },
      { fiscalYear: 2021, value: 172_000_000 },
      { fiscalYear: 2022, value: 251_000_000 },
      { fiscalYear: 2023, value: 331_000_000 },
      { fiscalYear: 2024, value: 412_000_000 },
    ],
    fcfHistory: [
      { fiscalYear: 2022, operatingCashFlow: 402_000_000, capex: -98_000_000 },
      { fiscalYear: 2023, operatingCashFlow: 512_000_000, capex: -112_000_000 },
      { fiscalYear: 2024, operatingCashFlow: 655_000_000, capex: -115_000_000 },
    ],
  },
  businessQuality: {
    economicEngineSummary: {
      text: "DEMO DATA — Aperture sells warehouse-automation robots plus a recurring software/maintenance subscription; hardware funds the installed base, software carries the margin.",
      confidence: "estimate",
    },
    primaryGrowthDrivers: ["market_share_gains", "new_products", "ai_demand"],
    growthDriverExplanation: {
      text: "DEMO DATA — growth is illustrated as coming from new warehouse-automation contracts and expanding software attach rate, not pricing.",
      confidence: "estimate",
    },
    primaryMarginDrivers: ["operating_leverage", "product_mix"],
    marginDriverExplanation: {
      text: "DEMO DATA — illustrative margin expansion from software mix shift and fixed-cost absorption at higher volume.",
      confidence: "estimate",
    },
    segmentEconomics: [
      { segment: "Hardware (demo)", note: "Lower margin, funds installed base." },
      { segment: "Software & Services (demo)", note: "Higher margin, recurring." },
    ],
    customerConcentration: { text: "DEMO DATA — top 10 customers illustrated at ~28% of revenue.", confidence: "estimate" },
    geographicConcentration: { text: "DEMO DATA — ~70% North America, ~30% international (illustrative).", confidence: "estimate" },
    capitalIntensity: { text: "DEMO DATA — moderate capex intensity, ~3.7% of revenue illustrated.", confidence: "estimate" },
    workingCapitalTrend: { text: "DEMO DATA — illustrative stable working capital as % of revenue.", confidence: "estimate" },
    recurringRevenueCharacter: { text: "DEMO DATA — illustrative ~35% of revenue is recurring software/service.", confidence: "estimate" },
  },
  moneyMachine: {
    qualityOfEarnings: "strong",
    qualityReasoning: {
      text: "DEMO DATA — operating cash flow growth has illustratively outpaced net income growth, a healthy sign in this demo.",
      confidence: "estimate",
    },
    discrepancyChecks: [
      { area: "accounts_receivable", observation: "DEMO DATA — no material divergence illustrated.", confidence: "unverified" },
      { area: "inventory", observation: "DEMO DATA — illustrative build consistent with revenue growth.", confidence: "unverified" },
      { area: "accounts_payable", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "deferred_revenue", observation: "DEMO DATA — illustrative growth in line with software attach rate.", confidence: "unverified" },
      { area: "capitalized_expenses", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "stock_compensation", observation: "DEMO DATA — illustrative SBC ~4% of revenue.", confidence: "unverified" },
      { area: "acquisitions", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "restructuring", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "one_time_gains", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "one_time_expenses", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
      { area: "tax_effects", observation: "DATA NOT AVAILABLE in this demo.", confidence: "unverified" },
    ],
    earningsQualityAlerts: [],
  },
  valuation: {
    valuationSummaryNarrative:
      "DEMO DATA — illustrates a company priced for continued double-digit growth; a real reverse DCF and price zones are computed live for any real ticker.",
    reverseDcf: {
      impliedRevenueGrowthPct: 16.4,
      impliedOperatingMarginPct: 22,
      impliedTerminalGrowthPct: 3,
      yearsModeled: 10,
      assumptionsNarrative:
        "DEMO DATA — at today's illustrative price, the market appears to require ~16% annual revenue growth for a decade at a ~22% operating margin.",
      methodologyNote:
        "Simplified reverse DCF (illustrative): constant growth, FCF margin held flat, 9% discount rate, 3% terminal growth.",
    },
    priceOpportunityZones: [
      { zone: "strong_value", rangeLow: null, rangeHigh: 48, rationale: "DEMO DATA — illustrative strong-value ceiling." },
      { zone: "attractive", rangeLow: 48, rangeHigh: 77, rationale: "DEMO DATA — illustrative attractive band." },
      { zone: "fair_value", rangeLow: 77, rangeHigh: 128, rationale: "DEMO DATA — illustrative fair-value band." },
      { zone: "expensive", rangeLow: 128, rangeHigh: 256, rationale: "DEMO DATA — illustrative expensive band." },
      { zone: "extreme_expectation", rangeLow: 256, rangeHigh: null, rationale: "DEMO DATA — illustrative extreme-expectation floor." },
    ],
    expectationGap: {
      marketImpliedSummary: "DEMO DATA — market-implied growth exceeds trailing 3-year CAGR in this illustration.",
      historicalPerformanceSummary: "DEMO DATA — revenue CAGR illustrated at ~21% over 3 years.",
      analystConsensusSummary: {
        text: "No licensed analyst consensus feed is connected — this field is always unverified until one is.",
        confidence: "unverified",
      },
      baseScenario: "DEMO DATA — growth moderates toward mid-teens as the installed base matures.",
      bullScenario: "DEMO DATA — software attach rate accelerates, re-rating the stock higher.",
      bearScenario: "DEMO DATA — hardware growth slows and margin expansion stalls.",
    },
  },
  investmentView: {
    view: "hold_watch",
    baseCaseLow: 78,
    baseCaseHigh: 96,
    bullCaseValue: 130,
    bearCaseValue: 52,
    timeHorizon: "3-5 years (demo)",
    confidenceLevel: "medium",
    businessQuality: "strong",
    financialQuality: "strong",
    valuationRisk: "high",
    earningsQuality: "strong",
    moatDirection: "strengthening",
    managementExecution: "mixed",
    expectationRisk: "high",
    whyNarrative:
      "DEMO DATA — the underlying business is illustrated as financially strong and improving competitively, but today's price already assumes aggressive growth continuing for years.",
  },
  moat: {
    moatDirection: "strengthening",
    moatNarrative: "DEMO DATA — illustrative expanding software/data advantage and rising switching costs as the installed base grows.",
    factors: [
      { factor: "data_advantage", evidence: "DEMO DATA — illustrative fleet-data feedback loop improving routing algorithms.", confidence: "estimate" },
      { factor: "switching_costs", evidence: "DEMO DATA — illustrative integration depth with customer warehouse systems.", confidence: "estimate" },
      { factor: "scale_advantages", evidence: "DEMO DATA — illustrative unit-cost decline with installed base growth.", confidence: "estimate" },
      { factor: "distribution", evidence: "DEMO DATA — illustrative direct sales + systems-integrator partnerships.", confidence: "estimate" },
    ],
    competitiveLandscapeNarrative: "DEMO DATA — illustrative fragmented competitive set with two larger incumbents and several well-funded startups.",
  },
  ceoPromiseTracker: {
    promises: [
      {
        statementText: "DEMO DATA — \"We expect operating margin to exceed 20% by fiscal 2024.\"",
        statementDate: "FY2022 earnings call (demo)",
        targetMetric: "Operating margin > 20%",
        actualOutcome: "Illustrated at 22% in FY2024",
        status: "achieved",
        confidence: "estimate",
      },
      {
        statementText: "DEMO DATA — \"International revenue should double within three years.\"",
        statementDate: "FY2022 investor day (demo)",
        targetMetric: "International revenue 2x within 3 years",
        actualOutcome: "Illustrated at +31% within 2 years",
        status: "behind_trajectory",
        confidence: "estimate",
      },
    ],
    executionRecord: { promisesTracked: 2, achieved: 1, partiallyAchieved: 0, missed: 0, pending: 1 },
    capitalAllocationHistory: [
      "DEMO DATA — one tuck-in acquisition illustrated in FY2023.",
      "DEMO DATA — modest buyback program illustrated, offsetting dilution from equity compensation.",
    ],
    strategicConsistencyNarrative: "DEMO DATA — illustrative consistent strategy across the period shown, no major pivots.",
  },
  institutional: {
    dataAvailable: true,
    notice: "DEMO DATA — illustrates what a connected 13F provider would show. Not a real filing.",
    reportingPeriod: "Q2 2025 (demo)",
    filingDate: "2025-08-14 (demo)",
    dataAgeDays: 90,
    institutionalOwnershipPct: 0.68,
    newPositions: 31,
    increasingPositions: 94,
    reducingPositions: 48,
    exitedPositions: 11,
    interpretation: "accumulation",
    topHolders: [
      { name: "Vanguard Group Inc (demo)", currentShares: 42_000_000, previousShares: 39_500_000, changeSharesPct: 0.063, classification: "increased" },
      { name: "BlackRock Inc (demo)", currentShares: 38_500_000, previousShares: 38_600_000, changeSharesPct: -0.003, classification: "unchanged" },
      { name: "State Street Corp (demo)", currentShares: 19_200_000, previousShares: 14_000_000, changeSharesPct: 0.371, classification: "conviction_increase" },
    ],
    isDemoData: true,
  },
  bull: {
    thesisStatement: "DEMO DATA — illustrative bull case: durable installed-base advantage compounding through a growing software attach rate.",
    strongestEvidence: [
      { point: "DEMO DATA — revenue CAGR illustrated at 21% over 3 years with expanding margins.", confidence: "estimate" },
      { point: "DEMO DATA — FCF conversion above 100% of net income illustrated, a healthy earnings-quality signal.", confidence: "estimate" },
      { point: "DEMO DATA — net cash balance sheet illustrated, giving flexibility for further investment or buybacks.", confidence: "estimate" },
    ],
    keyDrivers: ["DEMO DATA — software attach rate", "DEMO DATA — installed-base scale", "DEMO DATA — international expansion"],
  },
  bear: {
    attackStatement: "DEMO DATA — illustrative bear case: today's price already assumes a decade of premium growth that has never been sustained this long by a peer.",
    strongestEvidence: [
      { point: "DEMO DATA — reverse DCF implies ~16% growth for 10 years, well above typical industrial-automation base rates.", confidence: "estimate" },
      { point: "DEMO DATA — one management promise (international revenue) is illustrated as behind trajectory.", confidence: "estimate" },
      { point: "DEMO DATA — customer concentration illustrated at ~28% in the top 10 accounts, a real dependency risk if even a few churn.", confidence: "estimate" },
    ],
    keyRisks: ["DEMO DATA — valuation risk", "DEMO DATA — execution risk on international expansion", "DEMO DATA — customer concentration"],
  },
  judge: {
    classifiedClaims: [
      { claim: "DEMO DATA — revenue CAGR ~21% over 3 years", classification: "fact" },
      { claim: "DEMO DATA — reverse DCF implies ~16% growth needed for 10 years", classification: "estimate" },
      { claim: "DEMO DATA — international promise behind trajectory", classification: "fact" },
      { claim: "DEMO DATA — moat is strengthening", classification: "inference" },
      { claim: "DEMO DATA — no licensed analyst consensus available", classification: "unknown" },
      { claim: "DEMO DATA — net cash balance sheet", classification: "fact" },
    ],
    strongestBullPoint: "DEMO DATA — FCF conversion above net income, a real earnings-quality signal.",
    strongestBearPoint: "DEMO DATA — valuation requires a decade of premium growth rarely sustained in this industry.",
    unresolvedQuestions: ["DEMO DATA — can software attach rate keep accelerating as the base matures?"],
    criticalAssumptions: ["DEMO DATA — no major customer churn in the top 10 accounts."],
    informationGaps: ["DEMO DATA — no licensed institutional-ownership or analyst-consensus feed connected."],
  },
  icMemo: {
    executiveSummary: "DEMO DATA — illustrative memo for a fictional company, shown because no ANTHROPIC_API_KEY is configured or DEMO_MODE is enabled.",
    investmentThesis: "DEMO DATA — a durable, improving business whose current price already assumes a long runway of premium growth.",
    businessQualitySummary: "DEMO DATA — strong, improving unit economics illustrated.",
    financialQualitySummary: "DEMO DATA — strong cash conversion illustrated, low leverage.",
    valuationSummary: "DEMO DATA — priced for sustained double-digit growth; limited margin of safety illustrated.",
    managementSummary: "DEMO DATA — mostly consistent execution, one tracked promise behind trajectory.",
    moatSummary: "DEMO DATA — strengthening via data/switching-cost advantages as installed base grows.",
    institutionalActivitySummary: "DEMO DATA — illustrative net institutional accumulation.",
    positiveCatalysts: [{ description: "DEMO DATA — new large customer win", timing: "Next 2-4 quarters (demo)", confidence: "unverified" }],
    negativeCatalysts: [{ description: "DEMO DATA — slower international rollout", timing: "Ongoing (demo)", confidence: "unverified" }],
    risks: ["DEMO DATA — valuation risk", "DEMO DATA — customer concentration", "DEMO DATA — execution risk abroad"],
    bullCaseSummary: "DEMO DATA — software mix keeps expanding margins and justifies a re-rating higher.",
    baseCaseSummary: "DEMO DATA — growth moderates but the business remains high quality; price roughly fair.",
    bearCaseSummary: "DEMO DATA — growth disappoints and multiple compresses meaningfully.",
    marketExpectationsSummary: "DEMO DATA — market-implied growth exceeds the trailing 3-year trend.",
    upgradeConditions: ["DEMO DATA — revenue growth reaccelerates above 20%", "DEMO DATA — price falls into the attractive zone"],
    downgradeConditions: ["DEMO DATA — FCF margin falls below 10%", "DEMO DATA — top-10 customer concentration rises above 35%"],
    criticalUnknowns: ["DEMO DATA — real institutional 13F activity", "DEMO DATA — real analyst consensus"],
    sources: [{ label: "AARAN AI Demo Data", claimSupported: "This entire analysis is illustrative, not a real filing or a real company." }],
    generatedAt: new Date().toISOString(),
  },
};
